### ISSUE TITLE
Custom dependency types (or groups)

### ISSUE THREAD

**Issue by creynders** [yarnpkg/rfcs#13] opened 2016-10-25 13:02 UTC
Having a limited number of dependency types does not make sense in today's development process. If I look at a typical project of mine I have various stages and environments during development and deployment. Breaking this down into just `devDependencies` and `dependencies` seems very insufficient.

It would be awesome to be able to declare them as such, e.g.:

```
dependencies: {
  dev: {
    babel: 'v0.0.0'
  },
  uitest: {
    nightwatch: 'v0.0.0'
  },
  unittest: {
    mocha: 'v0.0.0'
  },
  core: {
    express: 'v0.0.0'
  }
}
```

(Nvm the API, it's all about the concept)

Just to be clear the keys `dev`, `uitest`, etc. are arbitrarily chosen as an example. What I'd want to propose is the possibility to use any word you want. And group them in any way you want.

Installation could be as easy as e.g. `yarn install --core --uitest --dev` i.e. just specifying which dependency types/groups/whatever you want to install. I.e. you'd combine the keys to specify which types you want installed. E.g. on your build server you could do `yarn install --core --dev`, on your testing server you'd do `yarn install --core --unittest --uitest` And so on.

And maybe you should be able to declare a `default` entry (i.e. what `dependencies` is in npm-land)

This would allow us to install only what's really necessary on each machine: local dev, QA, testing, staging, production, ...

**Comment by creynders** [comment] 2016-10-25 13:14
Originally posted at yarnpkg/yarn#1431

**Comment by thejameskyle** [comment] 2016-10-25 16:03
Ignoring some of the problems that would have to be resolved with various apis having different meanings with the existing dependency types. This would cause issues with your use case:

> This would allow us to install only what's really necessary on each machine: local dev, QA, testing, staging, production, ...

The problem is that dependencies almost never fall into just one of those categories. You can't just force them into buckets like that.

They also don't fall under just "Unit Testing" or "Core" unless you want to introduce dependencies of categories as well ("Unit Testing" would have to depend on "Core" in order to create the correct set of dependencies when installed). 

In general I don't think we need to get that religious about making sure that people install the exact minimum number of dependencies that they have declared for the environment they are in. We can make installs fast enough that it shouldn't matter beyond the first install (that's true for CI environments as well).

**Comment by creynders** [comment] 2016-10-25 16:27
Ah sorry, apparently my `install` example was vague. I meant you would be able to specidy multiple groups. I.e on my testing server I'd do `install --core --unittest --dev` and on my build env I'd only do `install --core --dev` etc. You'd mix and match.

**Comment by jamischarles** [comment] 2016-10-25 16:33
The only use case I've ever wanted this was for Webpack when it wasn't obvious that webpack deps need to go into `devdeps`. That specific case is an education / docs issue though imo. The big benefit I see with just having 2 types of deps is that it's very predictable, and once you learn the rules around those, you know how deps will be installed. Personally I wouldn't want to allow more custom dep types on my team.

**Comment by thejameskyle** [comment] 2016-10-25 16:46
There is documentation on the existing types of dependencies here: https://yarnpkg.com/en/docs/dependency-types

If anyone wants to improve that, just click on the "Edit this page" link on the bottom of the page.

**Comment by creynders** [comment] 2016-10-25 17:08
@Jamicharles yeah YMMV, but since using docker on back and front, having 5 different stages before deployment, using different kinds of tests ( e2e, integration, unit, smoke, etc) and having dependencies that only are needed in each of those, I've been wanting this. My guess is, others will too. But I think it depends on what you develop and how.

**Comment by creynders** [comment] 2016-10-25 17:13
@Thejameskyle having 4 different types already should be a red flag IMO that it's not such a crazy idea. I think this could be a clean way to get rid of those 4 insufficient as they are. One of the things I don't like about npm is their "There's only one true way" approach in choosing features, while I strongly believe the user should be in control, not the other way around.

**Comment by thejameskyle** [comment] 2016-10-25 17:17
Well....

1. We can never get rid of those 4 types of dependencies as they are extensively used in the ecosystem
2. Changing the way dependencies gets declared breaks the existing ecosystem
3. Those types of dependencies are well defined and allow for clean semantics across every type of packages 

Yarn is not here to break the ecosystem, that would really suck for everyone.

**Comment by creynders** [comment] 2016-10-25 17:17
@thejameskyle re-reading your first post, I think there's another thing I didn't make clear, I'm not proposing to have `unittest`, `core`, etc dependency types. These were just arbitrary names. I meant it could be whatever you want. What *you* need in your development workflow. Not what somebody else needs.
I'll update the original proposal to make it more clear.

**Comment by creynders** [comment] 2016-10-25 17:19
@thejameskyle and also, I'd never propose it to be backwards-breaking. Obviously those 4 types would still be available. And nobody'd had to use custom types if they don't want to.
Again, I'll update my proposal. 😁

**Comment by joshmanders** [comment] 2016-10-25 17:20
While I don't see a reason for these extra types, it would be kind of neat to have `*Dependencies` key, whether it's `devDependencies`, `peerDependencies` or `testDependencies`, you could use a flag or something to say "install anything set in this `*Dependencies` object` so if I did `yarn --dependencies=test` then it would install `testDependencies`

**Comment by creynders** [comment] 2016-10-25 17:27
@joshmanders sure. I'm not 100% sure about the syntax. Basically I just want more granular control on which dependencies get installed and which won't.

**Comment by monolithed** [comment] 2016-11-07 16:48
There's the same [issue](https://github.com/npm/npm/issues/13479) in npm.

**Comment by creynders** [comment] 2016-11-07 17:43
Cool thanks, hadn't encountered it yet!

**Comment by whitecolor** [comment] 2016-11-15 15:48
```json
dependencies: {

},
testDependencies: {

},
xxxDependencies: {

}
```

To install only prod dependencies and xxx:
```
> yarn --prod --deps xxx
```

**Comment by kittens** [comment] 2016-12-01 22:58
Closing this as this RFC has been created incorrectly. Please follow this [template](https://github.com/yarnpkg/rfcs/blob/master/0000-template.md) and submit a PR. See #16, #7, #1 for reference.

**Closed by kittens** 2016-12-01 22:58 UTC
